website: https://nkdagility.com/
basewebsite: /scrum-delivery-kit
baseurl: /scrum-delivery-kit
source: ./src
destination: ./_site

include:
 - "**/*.md"
 - "*.md"

plugins:
  - jekyll-relative-links

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

relative_links:
  enabled:     true
  collections: false