title: Agile Delivery Kit for Software Organisations
description: A starter agile delivery kit targeted at software organisations to help jump start creating a way or working that suits them.
tagline: A starter agile delivery kit targeted at software organisations to help jump start creating a way or working that suits them.
parent_title: naked Agility with Martin Hinshelwood
parent_url: https://nkdagility.com

website: https://nkdagility.com
baseurl: /learn/agile-delivery-kit
url: "https://nkdagility.com"
source: ./src
destination: ./_site
logo: https://nkdagility.com/wp-content/uploads/2020/11/nkdagility-with-martin-hinshelwood-dark-200.png
permalink: pretty

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/naked-agility-Learn-Agile-Delivery-Kit-1600x900.jpg
      toc: true
      
toc:
  min_level: 1
  max_level: 2
  ordered_list: false
  no_toc_section_class: no_toc_section
  list_id: toc
  list_class: section-nav bd-links-nav list-unstyled pb-1 small
  sublist_class: ''
  item_class: toc-entry align-items-center pb-2
  item_prefix: toc-

include:
 - "**/*.md"
 - "*.md"

plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-toc
  - jekyll-time-to-read
  # - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-last-modified-at

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  auto_ids: true

relative_links:
  enabled:     true
  collections: false