title: Agile Delivery Kit for Software Organisations
description: How to work in an agile way. This starter kit provides the strategies, recipes. workshops, technologies, practices, and guides that will help you and your people create a way of work that enables success.
tagline: How to work in an agile way\u003a principles, tools and governance. A template for a way of work.
parent_title: naked Agility with Martin Hinshelwood
parent_url: https://nkdagility.com

parent_title: naked Agility with Martin Hinshelwood
parent_url: https://nkdagility.com

website: https://nkdagility.com
baseurl: /learn/agile-delivery-kit
url: "https://nkdagility.com"
source: ./src
destination: ./_site
logo: https://nkdagility.com/wp-content/uploads/2020/11/nkdagility-with-martin-hinshelwood-dark-200.png
permalink: pretty

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/naked-agility-Learn-Agile-Delivery-Kit-1600x900.jpg
      toc: true
      
toc:
  min_level: 1
  max_level: 2
  ordered_list: false
  no_toc_section_class: no_toc_section
  list_id: toc
  list_class: section-nav bd-links-nav list-unstyled pb-1 small
  sublist_class: ''
  item_class: toc-entry align-items-center pb-2
  item_prefix: toc-

include:
 - "**/*.md"
 - "*.md"

plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-toc
  - jekyll-time-to-read
  # - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-last-modified-at

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  auto_ids: true

relative_links:
  enabled:     true
  collections: false