name: Build Docs

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  pull_request:
    branches:
    - main


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    environment:
      name: nakedalmweb-githubSDK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'
      - name: Display GitVersion config
        id:   gitversion # id to later be referenced
        uses: gittools/actions/gitversion/execute@v0
      - uses: actions/checkout@v2
      - uses: cschleiden/replace-tokens@v1
        with:
          files: '["**/*.html"]'
          tokenPrefix: "${"
          tokenSuffix: "}"
      - uses: igsekor/pyspelling-any@v1.0.4
        id: spellcheck
        name: Spellcheck
      - name: Build Jekyll
        uses: jerryjvl/jekyll-build-action@v1
      - uses: actions/upload-artifact@v3
        with:
          name: _site
          path: ./_site/**/*

  publish:
    needs: [build]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: _site
      - name: publish
        run: |
          echo 'publishing'