name: Deploy to WPEngine - Jekyll with dependencies preinstalled

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  pull_request:
    branches:
    - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./src
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1

  # Deployment job
  deplyWPEngine:
    environment:
      name: nakedalmweb-githubSDK
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SFTP Upload
        # You may pin to the exact commit or the version.
        # uses: Dylan700/sftp-upload-action@f90db607d9fe1acdc0eefccee84d37c119b268fe
        uses: Dylan700/sftp-upload-action@v1.1.4
        with:
          server: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: ${{ secrets.SFTP_PORT }}
          # If true, outputs the results of the upload, without actually uploading.
          dry-run: false
          # A list of folders to upload in the format of `folder/ => upload_folder/`
          uploads: | 
              ./_site/ => ./test-deploy/
          # If true, any existing files in the remote upload directories are deleted.
          delete: false

      #- name: SFTP Deploy
      #  # You may pin to the exact commit or the version.
      #  # uses: wlixcc/SFTP-Deploy-Action@da88a4dbe95286266bbac3c0b2b8284048d20c8f
      #  uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      #  with:
      #    # username
      #    username: ${{ secrets.SFTP_USERNAME }}
      #    # your sftp server
      #    server: ${{ secrets.SFTP_SERVER }}
      #    # your sftp server port, default to 22
      #    port: ${{ secrets.SFTP_PORT }}
      #    # will put all file under this path
      #    local_path: ./_site
      #    # files will copy to under remote_path
      #    remote_path: /test-deploy
      #    # SSH passsword，If a password is set, the secret key pair is ignored
      #    password: ${{ secrets.SFTP_PASSWORD }}