# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Validate SDK

on:
  pull_request:
    branches:
    - main
    
jobs:
  validate:
    name: Check SDK
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
      
      - uses: igsekor/pyspelling-any@v1.0.4
        id: spellcheck
        name: Spellcheck

      - name: PR Comment on failure only
        if: failure()
        # You may pin to the exact commit or the version.
        # uses: github-actions-up-and-running/pr-comment@f1f8ab2bf00dce6880a369ce08758a60c61d6c0b
        uses: github-actions-up-and-running/pr-comment@v1.0.1
        with:
          # GITHUB_TOKEN secret
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          # Message to comment
          message: "spell check failed check: https://github.com/nkdAgility/Scrum-Delivery-Kit-for-Software-Organisations/actions/workflows/main.yml" # ${{ steps.spellcheck.outputs }}
