# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Validate SDK

on:
  push:
    branches:
    - main
    
jobs:
  validate:
    name: Check SDK
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
      
      - uses: igsekor/pyspelling-any@v1.0.4
        name: Spellcheck


